# Generated by Django 2.0.2 on 2018-04-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='验证码'),
        ),
    ]
