# Generated by Django 2.0.2 on 2018-04-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_instructor_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='category',
            field=models.CharField(choices=[('personal', '个人'), ('vocational', '职业培训'), ('college', '高校')], default='personal', max_length=10, verbose_name='类别'),
        ),
    ]
