# Generated by Django 2.0.2 on 2018-04-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_org_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='enrolled_nums',
            field=models.IntegerField(default=0, verbose_name='注册学生人数'),
        ),
    ]
