# Generated by Django 2.0.2 on 2018-04-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_org_enrolled_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='course_nums',
            field=models.IntegerField(default=0, verbose_name='开放课程数量'),
        ),
    ]
