# Generated by Django 2.0.2 on 2018-05-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_org_course_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='image',
            field=models.ImageField(default='', max_length=200, upload_to='media/instructor/%Y/%m', verbose_name='头像'),
        ),
    ]
