# Generated by Django 2.0.2 on 2018-05-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='url',
            field=models.CharField(default='', max_length=300, verbose_name='视频地址'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='小节名'),
        ),
    ]
