# Generated by Django 2.0.2 on 2018-05-04 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='org',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Org', verbose_name='所属机构'),
        ),
    ]
