# Generated by Django 2.0.2 on 2018-05-04 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_instructor_image'),
        ('courses', '0015_remove_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Instructor', verbose_name='讲师'),
        ),
    ]
