# Generated by Django 2.0.2 on 2018-05-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='notice',
            field=models.CharField(default='', max_length=200, verbose_name='学前须知'),
        ),
        migrations.AddField(
            model_name='course',
            name='tips',
            field=models.CharField(default='', max_length=200, verbose_name='讲师提示'),
        ),
    ]
