# Generated by Django 2.0.2 on 2018-05-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20180507_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_ad',
            field=models.BooleanField(default=False, verbose_name='是否是广告客户'),
        ),
    ]
