# Generated by Django 2.0.2 on 2018-04-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourse',
            options={'verbose_name': '用户正在学习的课程', 'verbose_name_plural': '用户正在学习的课程'},
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '课程'), (2, '机构'), (3, '讲师')], default=1, verbose_name='收藏类型'),
        ),
    ]
