# Generated by Django 2.0.2 on 2018-05-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20180417_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[('course', '课程'), ('org', '机构'), ('teacher', '讲师')], default='course', verbose_name='收藏类型'),
        ),
    ]
