# Generated by Django 2.0.2 on 2018-05-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20180501_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.CharField(choices=[('course', '课程'), ('org', '机构'), ('teacher', '讲师')], default='course', max_length=10, verbose_name='收藏类型'),
        ),
    ]
